# Generated by Django 6.1.1 on 2026-09-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], max_length=10)),
                ('color', models.CharField(default='#4a90d9', help_text='Hex color for the profile avatar', max_length=7)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
    ]
