# Generated by Django 6.1.1 on 2026-09-07 19:08

from django.db import migrations

PROFILES = [
    {"name": "Mom", "role": "adult", "color": "#4a90d9"},
    {"name": "Dad", "role": "adult", "color": "#2e7d32"},
    {"name": "Emma", "role": "child", "color": "#e91e63"},
    {"name": "Max", "role": "child", "color": "#f57c00"},
]


def seed_profiles(apps, schema_editor):
    Profile = apps.get_model("chores", "Profile")
    for data in PROFILES:
        Profile.objects.get_or_create(name=data["name"], defaults=data)


def remove_profiles(apps, schema_editor):
    Profile = apps.get_model("chores", "Profile")
    Profile.objects.filter(name__in=[p["name"] for p in PROFILES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_profiles, remove_profiles),
    ]
