# Generated by Django 6.1.1 on 2026-09-07 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_seed_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('assignment_mode', models.CharField(choices=[('direct', 'Direct'), ('pool', 'Shared pool')], default='direct', max_length=10)),
                ('recurrence', models.CharField(choices=[('none', 'One-time'), ('daily', 'Daily'), ('weekly', 'Specific weekdays')], default='none', max_length=10)),
                ('weekdays', models.CharField(blank=True, help_text='Comma-separated weekday abbreviations, e.g. MON,WED,FRI (used when recurrence is weekly)', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('done', 'Done'), ('approved', 'Approved')], default='todo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'child'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='chores.profile')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'adult'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='chores.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
