# Generated by Django 6.1.1 on 2026-09-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='The day this generated instance is meant for', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The recurring task this one-off instance was generated from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chores.task'),
        ),
    ]
