# Generated by Django 6.1.1 on 2026-09-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_task_scheduled_date_task_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='after_photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_photos/after/'),
        ),
        migrations.AddField(
            model_name='task',
            name='before_photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_photos/before/'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('done', 'Pending approval'), ('approved', 'Approved')], default='todo', max_length=10),
        ),
    ]
