# Generated by Django 6.1.1 on 2026-09-07 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_task_after_photo_task_before_photo_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'adult'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to='chores.profile'),
        ),
    ]
